### ISSUE TITLE
Recurring sms [FEATURE]

### ISSUE THREAD

**Issue by 2SI3NX** [yeriomin/SmsScheduler#11]
Love the app you have made for us.
Is it possible you can add this feature of recurring sms sending? like every week for example.
And also together with that - it would be really useful if you could have an alarm or 'count-down' to remind the person that a sms will be sent at this specific recurring date, to give him the option of stopping the sms from sending or not. 
Please tell me you can do this?? it would be really useful and helpful. thanks

**Comment by davidhedlund** [comment]
I'm sure this will be the second most important feature of this add-on once implemented.

**Comment by davidhedlund** [comment]
You can copy the Repeat functionality from [https://f-droid.org/repository/browse/?fdfilter=Etar&fdid=ws.xsoh.etar Etar], or [https://f-droid.org/repository/browse/?fdfilter=Habits&fdid=org.isoron.uhabits Loop Habit Tracker].

**Comment by 2SI3NX** [comment]
so the repeat sms code functionality will work with another app at the same time or are you going to implement this soon?  the links dont work. thanks.

**Comment by yeriomin** [comment]
@2SI3NX 
>so the repeat sms code functionality will work with another app

No, copied code never works just like that. Its easier to write from scratch. I'll implement it, but right now I'm swamped.

**Comment by davidhedlund** [comment]
@yeriomin Cool.
