### ISSUE TITLE
Google Play link

### ISSUE THREAD

**Issue by Poussinou** [yeriomin/SmsScheduler#14]
Hi @yeriomin 

Can you provide a link to your official google play application?
There are a lot of applications on the Play Store that are the same, I just want to know which of them is the original one...

Then I'll give you a list of false apps and a link to report them to Google

Regards

**Comment by yeriomin** [comment]
Hi.

I never uploaded my app to Google Play Store. Anything you find on Play Store is not done by me. Play Store already had a number of apps which could schedule sms, but none of them were open source, that is why I decided to 1) write my own and 2) add it to f-droid and not Play Store.

[This one](https://play.google.com/store/apps/details?id=com.piloto.development.smsscheduler) stole my icon though 😄.

**Comment by yeriomin** [comment]
Oh wait.

[This one](https://play.google.com/store/apps/details?id=com.github.yeriomin.smsscheduler) is completely the same as mine. They didn't even change the package id.

I'm impressed.

**Comment by Poussinou** [comment]
Ok, that's what I thought...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v2 license and this guy is violating it;
* He is falsely claiming he made the app...

Maybe you should take some time (one hour or something so) to check the other apps about SMS Scheduling on Google Play Store, and report them to Google... Some of them are basically your app, with ads in it, and without GNU GPL, code source and your permission... If you do it, please copy-paste the links of the apps you reported in this thread, so that I can track the "Google developers" who are stealing your work. Thanks :smiley:
