### ISSUE TITLE
To field: Provide a contact register

### ISSUE THREAD

**Issue by davidhedlund** [yeriomin/SmsScheduler#15]
Thank you for your recent update, SMS Scheduler is really useful now.

I would like to have the possibility to select people from my contact list when I click on the "To:" field. This is standard in any SMS app so its feasible to request it.

**Comment by davidhedlund** [comment]
Sorry, its already there, I didn't notice the contact list until I clicked on the field.

**Comment by ghost** [comment]
@davidhedlund Where is the "contact list"?

**Comment by davidhedlund** [comment]
> @davidhedlund Where is the "contact list"?

Click in the "To field" and it should pop-up.
