### ISSUE TITLE
Support for Signal / LibreSignal and SMSSecure

### ISSUE THREAD

**Issue by SecUpwN** [yeriomin/SmsScheduler#2]
Good evening @yeriomin, thanks for developing this app and especially for directly publishing it on my beloved F-Droid app store! ;-) Here's my request: I would like your app to support sending _encrypted_ SMS via [Signal](https://github.com/WhisperSystems/Signal-Android) / [LibreSignal](http://www.kuketz-blog.de/?s=LibreSignal) and [SMSSecure](https://github.com/SMSSecure/SMSSecure). I am one of the privacy geeks out there who fully uninstalls the standard SMS app via [oandbackup](https://github.com/jensstein/oandbackup) and only use encrypted messengers. Not sure if this Issue will even be solvable since these messengers do protect the SMS database with a password. Maybe you can check?

Furthermore, would you please polish your app name a bit? For spelling consistency, it should say `SMSSechulder`both on your repository name, `README` and of course the real app name itself. Thanks and never let yourself down, I love that you're doing this effort for the open source community! :+1:

**Comment by yeriomin** [comment]
That's a very interesting suggestion! I will have to study these projects for a bit to know if it is possible.

**Comment by SecUpwN** [comment]
>That's a very interesting suggestion! I will have to study these projects for a bit to know if it is possible.

Thanks for considering it. Could you do tackle the renaming suggestion first? I am a very visual person.

**Comment by yeriomin** [comment]
Ok :). The user can see the README and the app name in the drawer/wherever. Its going to be "SMS Scheduler" there. Everywhere else is for developers, so a valid camelcase "SmsScheduler" is logical there.

**Comment by srguglielmo** [comment]
I'd also like to pop in and suggest Conversations as a supported encrypted client. I'm sure the developers of those apps would help!

Thank you!

**Comment by smichel17** [comment]
I'd imagine writing to an encrypted database would require duplicating the code from those messengers. That seems like a bunch of work and seems to run against the goal of protecting the privacy of your messages (because now there's another attack vector -- this app).

I think the "right" way to do this would be for the encrypted messengers to offer an intent for sending messages, so this app can just send the intent and then those apps can send the message and write to the database.

**Comment by yeriomin** [comment]
@smichel17 is exactly right.
Also, the mentioned projects:
* are huge, while I try to keep my apps very small
* have their own transport for messages, while my app uses plain old sms
* don't run on old phones(I could install SMSSecure on my HTC Desire, but it crashes), while I would like to provide apps for them

Sorry, that's a "Won't fix".
