### ISSUE TITLE
Delivery reports are on?

### ISSUE THREAD

**Issue by valerio-bozzolan** [yeriomin/SmsScheduler#3]
Thanks for this Free as in Freedom software. I've tried this from F-Droid. I «have that friend».. ;)

Only one thing: it seems that delivery reports are enabled by default.
Can you add an option to disable it? It costs for cetain carriers (in Italy, all the carriers)...

**Comment by yeriomin** [comment]
Thanks for your interest in the app!
"It costs for cetain carriers" - didn't know that. Added delivery reports as an option. Off by default.

**Comment by valerio-bozzolan** [comment]
Thanks!

Only to be known... Here they costs ~0.15€ each! °^°
