### ISSUE TITLE
Shedule is not working properly

### ISSUE THREAD

**Issue by vvishnu-e** [yeriomin/SmsScheduler#5]
I scheduled an sms on 07:00 am, but sms sent on 08:58 am (when i unlocked the phone).

I am using OnePlus One with Cyanogenmod 12.1

**Comment by yeriomin** [comment]
Should be fixed in 0.5. If not, check your settings, aggressive battery saving/dose mode. They **will** interfere.

**Comment by Alex-Esko** [comment]
Github: Actually disabling aggressive battery saving is a very important advice. I tested it yesterday, the phone was locked and charging and sending failed. After disabling aggressive battery saving, it worked like a charm.
An advice in the app would be perfect.
